### ISSUE TITLE
ZXP INSTALLER ISSUE

### ISSUE THREAD

**Issue by rburtin** [guideguide/ZXPInstaller#57]
I am trying to install a motion bro extension into premiere pro but every time I try to use the zxp installer it says, "Installation failed because the extension is not compatible with the installed applications." Any suggestions or a direct contact for ZXP ?

**Comment by arielgmpublicidad** [comment]
Estoy tratando de instalar una extensión de Motion factory en after effects, pero cada vez que trato de usar el instalador zxp dice: "La instalación falló porque la extensión no es compatible con las aplicaciones instaladas". ¿Alguna sugerencia o un contacto directo para ZXP?

**Comment by cameronmcefee** [comment]
This is a question for the plugin creator. They should be able to provide suggestions.
