### ISSUE TITLE
No compatible applications found on your system.

### ISSUE THREAD

**Issue by MichaelMatamoros** [guideguide/ZXPInstaller#59]
Had BG Renderer Max installed previously. Got error code 205 for After Effects. Had to do clean install of CC and After Effects. ZXP no longer detecting After Effects. Returning the rror code "Please install a compatible CC application and try again.
<img width="790" alt="Screen Shot 2019-09-17 at 11 59 04 AM" src="https://user-images.githubusercontent.com/5643126/65058703-b3da2e00-d942-11e9-82ae-29fef2136b68.png">
<img width="796" alt="Screen Shot 2019-09-17 at 11 58 51 AM" src="https://user-images.githubusercontent.com/5643126/65058704-b3da2e00-d942-11e9-91f4-64521b7a1ee2.png">

**Comment by cameronmcefee** [comment]
This is a question for the plugin creator. They should be able to provide suggestions.
